spring.application.name=spring_mvc_boot

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/task_spring_mvc_hibernate?\
                                                verifyServerCertificate=false&\
                                                useSSL=false&\
                                                requireSSL=false&\
                                                useLegacyDatetimeCode=false&amp&serverTimezone=UTC&\
                                                allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

# hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update

# for work -> hidden=_method (HTTP -> PUT, PATCH, DELETE)
spring.mvc.hiddenmethod.filter.enabled=true

# logs
#logging.level.org.springframework=debug
#logging.level.org.hibernate=debug

# init DB
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data(create_admin).sql

# cache view
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
# cache css
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
# boot 4 read target/static  need to show
spring.web.resources.static-locations=file:src/main/resources/static/